// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practica04.Models;

namespace Practica04.Migrations
{
    [DbContext(typeof(RegistroContext))]
    partial class RegistroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Practica04.Models.FormularioIngreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FormularioIngresos");
                });

            modelBuilder.Entity("Practica04.Models.FormularioRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormularioIngresoId")
                        .HasColumnType("int");

                    b.Property<string>("comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subidopor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulofoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("urlfoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FormularioIngresoId");

                    b.ToTable("FormularioRegistros");
                });

            modelBuilder.Entity("Practica04.Models.FormularioRegistro", b =>
                {
                    b.HasOne("Practica04.Models.FormularioIngreso", "FormularioIngreso")
                        .WithMany("FormularioRegistros")
                        .HasForeignKey("FormularioIngresoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormularioIngreso");
                });

            modelBuilder.Entity("Practica04.Models.FormularioIngreso", b =>
                {
                    b.Navigation("FormularioRegistros");
                });
#pragma warning restore 612, 618
        }
    }
}
